### PR TITLE
Include copy to another path

### PR DESCRIPTION
**Pull request by speduardo**
include copy to another path

### CODE REVIEW

**Comment by an-rahulpandey** [comment]
@speduardo Thanks for the pull request. Can you give me the usage example? Like if the db is in the www directory what will be the path or if the db is at some other location then what will be the path?

**Comment by speduardo** [comment]
por exemplo: eu coloco o db fora do projeto, um dos motivos é pra diminuir o tamanho do apk e outro flexibilidade para o usuário.

outro ponto é copiar o db interno da aplicacao para uma pasta externa

**Comment by speduardo** [comment]
sory

for example : I put the db out of the project , one reason is to reduce the apk size and other flexibility for the user .

another point is to copy the internal db of application to an external folder

**Comment by an-rahulpandey** [comment]
Can you show me the code, also I think the Pull request is incomplete, I do not see the usage of path variable in copyDBFrom function.

**Comment by speduardo** [comment]
I`m commit all

**Comment by speduardo** [comment]
i finish the code, but i don't get commit the code

**Comment by speduardo** [comment]
tell me your email to sent the code

**Comment by an-rahulpandey** [comment]
Yes, this is my email rahul.p@applicationnexus.com

**Comment by faridlab** [comment]
It would be great, if this pull request be merged ASAP.
Thanks for both of you.

**Comment by an-rahulpandey** [comment]
I haven't yet test the new code, but I have added the code in dev branch. You can download it from here and let me know how it goes when you test it.

**Pull request closed without merging**
